### ISSUE TITLE
Фрукты

### ISSUE THREAD

**Issue by milkina** [DashaYegorova/Homeworks#2]
Следующий код повторяется три раза:
        double apricotsCost = 0;
        for (Fruit apricots1 : apricots) {
            apricotsCost += apricots1.cost(apricots1);
        }

можно вынести в отдельный статический метод класса Fruit.

**Comment by DashaYegorova** [comment]
https://github.com/DashaYegorova/Homeworks/blob/master/lesson12/fruitShop/Fruit.java
Переделала
